environment: production

apphost: k8s

label:
  name: pocback

container:
  name: backend
  pullPolicy: Always
  image: pocdeployacr.azurecr.io/pocdeploy:latest
  tag: latest
  port: 80
replicas: 1

service:
  port: 8888
  type: LoadBalancer
